[workspace]
members = ["crates/nerd-font-symbols", "crates/generator"]

[workspace.package]
authors = ["Asger Juul Brunshøj"]
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"
